CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS tr_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(100) NOT NULL,
    tenant_name VARCHAR(255) NOT NULL,
    tenant_type VARCHAR(50),
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    remark TEXT,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_tenant_code UNIQUE (tenant_code)
);

CREATE TABLE IF NOT EXISTS tr_space (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_code VARCHAR(100) NOT NULL,
    space_name VARCHAR(255) NOT NULL,
    space_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    sort_no INTEGER NOT NULL DEFAULT 0,
    remark TEXT,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_space_tenant_code UNIQUE (tenant_id, space_code)
);

CREATE TABLE IF NOT EXISTS tr_user_space (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    space_id BIGINT NOT NULL,
    role_id BIGINT,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_user_space UNIQUE (tenant_id, user_id, space_id)
);

CREATE TABLE IF NOT EXISTS tr_org_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    username VARCHAR(100) NOT NULL,
    real_name VARCHAR(100),
    password_hash VARCHAR(255),
    mobile VARCHAR(50),
    email VARCHAR(255),
    avatar_url VARCHAR(500),
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    last_login_time TIMESTAMP,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_org_user_tenant_username UNIQUE (tenant_id, username)
);

CREATE TABLE IF NOT EXISTS tr_org_dept (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    parent_id BIGINT,
    dept_code VARCHAR(100) NOT NULL,
    dept_name VARCHAR(255) NOT NULL,
    leader_user_id BIGINT,
    sort_no INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_org_dept_tenant_code UNIQUE (tenant_id, dept_code)
);

CREATE TABLE IF NOT EXISTS tr_org_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    position_code VARCHAR(100) NOT NULL,
    position_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    sort_no INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_org_position_tenant_code UNIQUE (tenant_id, position_code)
);

CREATE TABLE IF NOT EXISTS tr_org_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    role_code VARCHAR(100) NOT NULL,
    role_name VARCHAR(255) NOT NULL,
    role_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    sort_no INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_org_role_tenant_code UNIQUE (tenant_id, role_code)
);

CREATE TABLE IF NOT EXISTS tr_org_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_org_user_role UNIQUE (tenant_id, user_id, role_id)
);

CREATE TABLE IF NOT EXISTS tr_org_user_dept (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    dept_id BIGINT NOT NULL,
    primary_flag SMALLINT NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_org_user_dept UNIQUE (tenant_id, user_id, dept_id)
);

CREATE TABLE IF NOT EXISTS tr_permission_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    resource_code VARCHAR(150) NOT NULL,
    resource_name VARCHAR(255) NOT NULL,
    resource_type VARCHAR(50) NOT NULL,
    parent_id BIGINT,
    path VARCHAR(500),
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    sort_no INTEGER NOT NULL DEFAULT 0,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_permission_resource UNIQUE (tenant_id, space_id, resource_code)
);

CREATE TABLE IF NOT EXISTS tr_permission_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    policy_code VARCHAR(150) NOT NULL,
    policy_name VARCHAR(255) NOT NULL,
    policy_type VARCHAR(50) NOT NULL,
    effect VARCHAR(20) NOT NULL DEFAULT 'ALLOW',
    condition_json JSONB,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_permission_policy UNIQUE (tenant_id, space_id, policy_code)
);

CREATE TABLE IF NOT EXISTS tr_permission_role_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    role_id BIGINT NOT NULL,
    resource_id BIGINT NOT NULL,
    action_code VARCHAR(100) NOT NULL DEFAULT 'VIEW',
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_permission_role_resource UNIQUE (tenant_id, space_id, role_id, resource_id, action_code)
);

CREATE TABLE IF NOT EXISTS tr_permission_data_scope (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    role_id BIGINT NOT NULL,
    object_type_id BIGINT,
    data_scope VARCHAR(50) NOT NULL,
    custom_rule_json JSONB,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tr_permission_field (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    role_id BIGINT NOT NULL,
    object_type_id BIGINT NOT NULL,
    field_code VARCHAR(100) NOT NULL,
    visible_flag SMALLINT NOT NULL DEFAULT 1,
    editable_flag SMALLINT NOT NULL DEFAULT 0,
    masked_flag SMALLINT NOT NULL DEFAULT 0,
    ai_readable_flag SMALLINT NOT NULL DEFAULT 0,
    ai_writable_flag SMALLINT NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_permission_field UNIQUE (tenant_id, space_id, role_id, object_type_id, field_code)
);

CREATE TABLE IF NOT EXISTS tr_permission_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    user_id BIGINT,
    resource_type VARCHAR(50),
    resource_code VARCHAR(150),
    action_code VARCHAR(100),
    result VARCHAR(50),
    reason TEXT,
    context_json JSONB,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tr_dict_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    dict_code VARCHAR(100) NOT NULL,
    dict_name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    remark TEXT,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_dict_type UNIQUE (tenant_id, dict_code)
);

CREATE TABLE IF NOT EXISTS tr_dict_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    dict_code VARCHAR(100) NOT NULL,
    item_code VARCHAR(100) NOT NULL,
    item_name VARCHAR(255) NOT NULL,
    item_value VARCHAR(255),
    sort_no INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    remark TEXT,
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_tr_dict_item UNIQUE (tenant_id, dict_code, item_code)
);

CREATE TABLE IF NOT EXISTS tr_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    file_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255),
    file_ext VARCHAR(50),
    file_size BIGINT,
    storage_type VARCHAR(50) NOT NULL DEFAULT 'LOCAL',
    storage_path VARCHAR(1000),
    content_type VARCHAR(255),
    biz_type VARCHAR(100),
    biz_id BIGINT,
    status VARCHAR(50) NOT NULL DEFAULT 'ENABLED',
    created_by BIGINT,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_flag SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tr_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    space_id BIGINT,
    object_type VARCHAR(100),
    object_id BIGINT,
    action_type VARCHAR(100) NOT NULL,
    action_name VARCHAR(255),
    operator_id BIGINT,
    operator_name VARCHAR(100),
    before_json JSONB,
    after_json JSONB,
    diff_json JSONB,
    ip VARCHAR(100),
    device VARCHAR(255),
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tr_space_tenant ON tr_space (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tr_user_space_user ON tr_user_space (tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_tr_org_user_tenant ON tr_org_user (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tr_org_dept_tenant_parent ON tr_org_dept (tenant_id, parent_id);
CREATE INDEX IF NOT EXISTS idx_tr_org_role_tenant ON tr_org_role (tenant_id);
CREATE INDEX IF NOT EXISTS idx_tr_permission_resource_tenant ON tr_permission_resource (tenant_id, space_id);
CREATE INDEX IF NOT EXISTS idx_tr_permission_policy_tenant ON tr_permission_policy (tenant_id, space_id);
CREATE INDEX IF NOT EXISTS idx_tr_file_biz ON tr_file (tenant_id, space_id, biz_type, biz_id);
CREATE INDEX IF NOT EXISTS idx_tr_audit_log_object ON tr_audit_log (tenant_id, space_id, object_type, object_id);
