export default [
  {
    path: '/login',
    component: '@/pages/Login/index.tsx',
    layout: false,
  },
  {
    path: '/platform/login',
    component: '@/pages/Login/index.tsx',
    layout: false,
  },
  {
    path: '/enterprise/login',
    component: '@/pages/Login/index.tsx',
    layout: false,
  },
  {
    path: '/workspace/login',
    component: '@/pages/Login/index.tsx',
    layout: false,
  },
  {
    path: '/',
    component: '@/layouts/BasicLayout',
    routes: [
      { path: '/', redirect: '/workspace/home' },
      { path: '/space/config', component: '@/pages/Space/SpaceConfigPage.tsx' },
      { path: '/space/list', component: '@/pages/Space/SpaceListPage.tsx' },
      { path: '/space/nav-config', component: '@/pages/Space/SpaceNavConfigPage.tsx' },
      { path: '/space/work-items/:workItemTypeId/new', component: '@/pages/WorkItem/WorkItemRecordFormPage.tsx' },
      { path: '/space/work-items/:workItemTypeId/:recordId/edit', component: '@/pages/WorkItem/WorkItemRecordFormPage.tsx' },
      { path: '/space/work-items/:workItemTypeId/:recordId', component: '@/pages/WorkItem/WorkItemRecordFormPage.tsx' },
      { path: '/space/work-items/:workItemTypeId', component: '@/pages/WorkItem/WorkItemRecordListPage.tsx' },
      { path: '/platform/tenants', component: '@/pages/Platform/TenantList.tsx' },
      { path: '/platform/tenants/:id', component: '@/pages/Platform/TenantDetail.tsx' },
      { path: '/enterprise/users', component: '@/pages/Enterprise/UserList.tsx' },
      { path: '/enterprise/users/:id', component: '@/pages/Enterprise/UserDetail.tsx' },
      { path: '/enterprise/spaces', component: '@/pages/Enterprise/SpaceList.tsx' },
      { path: '/enterprise/spaces/:id', component: '@/pages/Enterprise/SpaceDetail.tsx' },
      { path: '/enterprise/permissions/tenant-templates', component: '@/pages/Enterprise/Permission/TenantDefaultTemplatePage.tsx' },
      { path: '/enterprise/permissions/tenant-features', component: '@/pages/Enterprise/Permission/TenantFeatureTogglePage.tsx' },
      { path: '/enterprise/permissions/space', component: '@/pages/Enterprise/Permission/SpacePermissionPage.tsx' },
      { path: '/workspace', component: '@/pages/Workspace/WorkspaceHome.tsx' },
      { path: '/workspace/home', component: '@/pages/Workspace/WorkspaceHome.tsx' },
      { path: '/workspace/spaces/:id/home', component: '@/pages/Workspace/WorkspaceSpaceHome.tsx' },
      { path: '*', redirect: '/space/config' },
    ],
  },
];
